routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DesaController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProvinsiController;
use App\Http\Controllers\KecamatanController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',[HomeController::class, 'index']);
Route::get('/desa', [DesaController::class, 'index']);
Route::get('/kecamtan', [KecamatanController::class, 'index']);
Route::get('/kabupaten', [KabupatenController::class, 'index']);
Route::get('/provinsi', [ProvinsiController::class, 'index']);


Route::resource('/desa', App\http\Controllers\DesaController::class)->except('show');;
Route::resource('/kecamatan', App\http\Controllers\KecamatanController::class)->except('show');;
Route::resource('/kabupaten', App\http\Controllers\KabupatenController::class)->except('show');;
Route::resource('/provinsi', App\http\Controllers\ProvinsiController::class)->except('show');;

app/Models/kabupaten.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class kabupaten extends Model
{
    use HasFactory;
    protected $fillable = ['kabupaten'];
    public $timestamps = false;

    public function scopeFilter($query, array $filters)
    {

        $query->when($filters['provinsi'] ?? false, function($query,$provinsi){
                return $query->whereHas('profinsi', function($query) use ($provinsi) {
                    $query->where('id', $provinsi);
                });
            });
    }

    public function provinsi(){
        return $this->belongsTo(provinsi::class);
    }

    public function kecamatan(){
        return $this->hasMany(kecamatan::class);
    }

    public function desa(){
        return $this->hasMany(desa::class);
    }

}

app/Http/Controllers/KabupatenController.php
<?php

namespace App\Http\Controllers;

use App\Models\provinsi;
use App\Models\kabupaten;
use Illuminate\Http\Request;

class KabupatenController extends Controller
{
    public function index()
    {
        $kabupatens = kabupaten::with(['provinsi'])->get();
        return view('kabupaten.index',compact('kabupatens'));

    }

    public function create()
    {
        return view('kabupaten.create',[
            'provinsis' => provinsi::all()
        ]);

    }

    public function store(Request $request)
    {
        $request->validate([
            'kabupaten' => 'required|string|max:255',
            'provinsi_id' => 'required|integer',
        ]);

        Kabupaten::create($request->all());
        return redirect()->route('kabupaten.index')->with('success', 'Kabupaten has been added!');
    }

    public function edit(Kabupaten $kabupaten)
    {
        return view('kabupaten.edit',[
            'kabupaten' => $kabupaten,
            'provinsis' => provinsi::all()
        ]);

    }

    public function update(Request $request, Kabupaten $kabupaten)
    {
        $request->validate([
            'kabupaten' => 'required|string|max:255',
            'provinsi_id' => 'required|integer',
        ]);

        $kabupaten->update($request->all());

        return redirect()->route('kabupaten.index')->with('success', 'Kabupaten telah berhasil diupdate');


    }

    public function destroy(Kabupaten $kabupaten)
    {
        $kabupaten->delete();

        return redirect()->route('kabupaten.index')->with('Success', 'kabupaten Berhasil di Hapus');
    }
}

resources/views/kabupaten/create.blade.php
@extends('layouts.main')

@section('container')

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Create New Kabupaten</h1>
  </div>

  <div class="col-lg-8">
  <form method="post" action="{{ route('kabupaten.store') }}" class="mb-5" enctype="multipart/form-data">
    @csrf
    <div class="mb-3">
      <label for="kabupaten" class="form-label">Nama</label>
      <input type="text" class="form-control" id="kabupaten"
      name="kabupaten">
    </div>
    <div class="mb-3">
        <label for="provinsi" class="form-tabel">Provinsi</label>
        <select class="form-select" name="provinsi_id">
            @foreach($provinsis as $provinsi)
            @if(old('provinsi_id') == $provinsi->id)
               <option value="{{ $provinsi->id }}" selected>{{ $provinsi->provinsi }}</option>
               @else
               <option value="{{ $provinsi->id }}">{{ $provinsi->provinsi }}</option>
               @endif
            @endforeach
        </select>
      </div>
    <button type="submit" class="btn btn-primary">Create Provinsi</button>
  </form>
</div>
@endsection

resources/views/kabupaten/edit.blade.php
@extends('layouts.main')

@section('container')

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Edit Provinsi</h1>
  </div>

  <div class="col-lg-8">
  <form method="post" action="{{ route('kabupaten.update', $kabupaten->id) }}" class="mb-5"
    enctype="multipart/form-data">
    @csrf
    @method('put')
    <div class="mb-3">
      <label for="kabupaten" class="form-label">Nama</label>
      <input type="text" class="form-control" id="kabupaten"
      name="kabupaten">
    </div>
    <div class="mb-3">
        <label for="provinsi" class="form-tabel">Provinsi</label>
        <select class="form-select" name="provinsi_id">
            @foreach($provinsis as $provinsi)
            @if(old('provinsi_id') == $provinsi->id)
               <option value="{{ $provinsi->id }}" selected>{{ $provinsi->provinsi }}</option>
               @else
               <option value="{{ $provinsi->id }}">{{ $provinsi->provinsi }}</option>
               @endif
            @endforeach
        </select>
      </div>
    <button type="submit" class="btn btn-primary">Update Provinsi</button>
  </form>
</div>
@endsection

resources/views/kabupaten/index.blade.php
@extends('layouts.main')


@section('container')
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Kabupaten</h1>
  </div>


@if(session()->has('success'))
    <div class="alert alert-success col-lg-6" role="alert">
    {{  session('success') }}
    </div>
@endif
  <div class="table-responsive col-lg-6">
      <a href="{{ route('kabupaten.create') }}" class="btn btn-primary mb-3">Create New Kabupaten</a>
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Name</th>

          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
          @foreach ($kabupatens as $kabupaten)
          <tr>
            <td>{{ $kabupaten->id}}</td>
            <td>{{ $kabupaten->kabupaten}}</td>

            <td>
                <a href="{{ route('kabupaten.edit',$kabupaten->id) }}" class="badge bg-warning">
                <span data-feather="edit"></span></a>
                <form action="{{ route('kabupaten.destroy',$kabupaten->id)}}" method="post" class="d-inline">
                @method('delete')
                @csrf
                <button class="badge bg-danger border-0" onclick="return confirm('Are you sure ?')">
                <span data-feather="x-circle"></span></button>
                </form>
            </td>
          </tr>
          @endforeach

      </tbody>
    </table>
  </div>
@endsection