routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DesaController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProvinsiController;
use App\Http\Controllers\KecamatanController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',[HomeController::class, 'index']);
Route::get('/desa', [DesaController::class, 'index']);
Route::get('/kecamtan', [KecamatanController::class, 'index']);
Route::get('/kabupaten', [KabupatenController::class, 'index']);
Route::get('/provinsi', [ProvinsiController::class, 'index']);


Route::resource('/desa', App\http\Controllers\DesaController::class)->except('show');;
Route::resource('/kecamatan', App\http\Controllers\KecamatanController::class)->except('show');;
Route::resource('/kabupaten', App\http\Controllers\KabupatenController::class)->except('show');;
Route::resource('/provinsi', App\http\Controllers\ProvinsiController::class)->except('show');;

app/Models/provinsi.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class provinsi extends Model
{
    use HasFactory;
    protected $fillable = ['id','provinsi'];
    public $timestamps = false;

    public function kabupaten(){
        return $this->hasMany(kabupaten::class);
    }

    public function kecamatan(){
        return $this->hasMany(kecamatan::class);
    }

    public function desa(){
        return $this->hasMany(desa::class);
    }

}

app/Http/Controllers/ProvinsiController.php
<?php

namespace App\Http\Controllers;

use App\Models\provinsi;
use Illuminate\Http\Request;

class ProvinsiController extends Controller
{
    public function index()
    {

        return view('provinsi.index',[
        'provinsis' => Provinsi::all()
    ]);

    }

    public function read(){
        $provinsis = provinsi::all();
        return view('welcome', compact('provinsis'));
    }

    public function create()
    {
        return view('provinsi.create');

    }

    public function store(Request $request)
    {
        $request->validate([
            'provinsi' => 'required|string|max:255',


        ]);

        Provinsi::create($request->all());
        return redirect()->route('provinsi.index')->with('success', 'Provinsi has been added!');
    }

    public function edit(Provinsi $provinsi)
    {
        return view('provinsi.edit', compact('provinsi'));

    }

    public function update(Request $request, Provinsi $provinsi)
    {
        $request->validate([
            'provinsi' => 'required|string|max:255',
        ]);

        $provinsi->update($request->all());

        return redirect()->route('provinsi.index')->with('success', 'Provinsi telah berhasil diupdate');


    }

    public function destroy(Provinsi $provinsi)
    {
        $provinsi->delete();

        return redirect()->route('provinsi.index')->with('Success', 'Provinsi Berhasil di Hapus');
    }
}

resources/views/provinsi/create.blade.php
@extends('layouts.main')

@section('container')

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Create New Provinsi</h1>
  </div>

  <div class="col-lg-8">
  <form method="post" action="{{ route('provinsi.store') }}" class="mb-5" enctype="multipart/form-data">
    @csrf
    <div class="mb-3">
      <label for="provinsi" class="form-label">Nama</label>
      <input type="text" class="form-control" id="provinsi"
      name="provinsi">
    </div>
    <button type="submit" class="btn btn-primary">Create Provinsi</button>
  </form>
</div>
@endsection

resources/views/provinsi/edit.blade.php
@extends('layouts.main')

@section('container')

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Edit Provinsi</h1>
  </div>

  <div class="col-lg-8">
  <form method="post" action="{{ route('provinsi.update', $provinsi->id) }}" class="mb-5"
    enctype="multipart/form-data">
    @csrf
    @method('put')
    <div class="mb-3">
      <label for="provinsi" class="form-label">Nama</label>
      <input type="text" class="form-control" id="provinsi"
      name="provinsi">
    </div>
    <button type="submit" class="btn btn-primary">Update Provinsi</button>
  </form>
</div>
@endsection

resources/views/provinsi/index.blade.php
@extends('layouts.main')


@section('container')
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Indonesia</h1>
  </div>


@if(session()->has('success'))
    <div class="alert alert-success col-lg-6" role="alert">
    {{  session('success') }}
    </div>
@endif
  <div class="table-responsive col-lg-6">
      <a href="{{ route('provinsi.create') }}" class="btn btn-primary mb-3">Create New Provinsi</a>
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Name</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
          @foreach ($provinsis as $provinsi)
          <tr>
            <td>{{ $provinsi->id }}</td>
            <td>{{ $provinsi->provinsi}}</td>
            <td>
                <a href="{{ route('provinsi.edit',$provinsi->id) }}" class="badge bg-warning">
                <span data-feather="edit"></span></a>
                <form action="{{ route('provinsi.destroy',$provinsi->id)}}" method="post" class="d-inline">
                @method('delete')
                @csrf
                <button class="badge bg-danger border-0" onclick="return confirm('Are you sure ?')">
                <span data-feather="x-circle"></span></button>
                </form>
            </td>
          </tr>
          @endforeach

      </tbody>
    </table>
  </div>
@endsection