routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DesaController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProvinsiController;
use App\Http\Controllers\KecamatanController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',[HomeController::class, 'index']);
Route::get('/desa', [DesaController::class, 'index']);
Route::get('/kecamtan', [KecamatanController::class, 'index']);
Route::get('/kabupaten', [KabupatenController::class, 'index']);
Route::get('/provinsi', [ProvinsiController::class, 'index']);


Route::resource('/desa', App\http\Controllers\DesaController::class)->except('show');;
Route::resource('/kecamatan', App\http\Controllers\KecamatanController::class)->except('show');;
Route::resource('/kabupaten', App\http\Controllers\KabupatenController::class)->except('show');;
Route::resource('/provinsi', App\http\Controllers\ProvinsiController::class)->except('show');;

app/Models/kecamatan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class kecamatan extends Model
{
    use HasFactory;
    protected $fillable = ['id','kecamatan'];
    public $timestamps = false;

    public function kabupaten(){
        return $this->belongsTo(kabupaten::class);
    }

    public function desa(){
        return $this->hasMany(desa::class);
    }

}

app/Http/Controllers/KecamatanController.php
<?php

namespace App\Http\Controllers;

use App\Models\kabupaten;
use App\Models\provinsi;
use App\Models\kecamatan;
use Illuminate\Http\Request;

class KecamatanController extends Controller
{
    public function index()
    {

        return view('kecamatan.index',[
        'kecamatans' => Kecamatan::all()
    ]);

    }

    public function create()
    {
        return view('kecamatan.create',[
            'provinsis' => provinsi::all(),
            'kabupatens' => kabupaten::all()
        ]);

    }

    public function store(Request $request)
    {
        $request->validate([
            'kecamatan' => 'required|string|max:255',
            'provinsi_id' => 'required|integer',
            'kabupaten_id' => 'required|integer',
        ]);

        Kecamatan::create($request->all());
        return redirect()->route('kecamatan.index')->with('success', 'Kecamatan has been added!');
    }

    public function edit(Kecamatan $kecamatan)
    {
        return view('kecamatan.edit',[
            'kecamatan' => $kecamatan,
            'provinsis' => provinsi::all(),
            'kabupatens' => kabupaten::all()
        ]);

    }

    public function update(Request $request, Kecamatan $kecamatan)
    {
        $request->validate([

            'kecamatan' => 'required|string|max:255',
            'provinsi_id' => 'required|integer',
            'kabupaten_id' => 'required|integer',
        ]);

        $kecamatan->update($request->all());

        return redirect()->route('kecamatan.index')->with('success', 'Kecamatan telah berhasil diupdate');


    }

    public function destroy(Kecamatan $kecamatan)
    {
        $kecamatan->delete();

        return redirect()->route('kecamatan.index')->with('Success', 'Kecamatan Berhasil di Hapus');
    }
}

resources/views/kecamatan/create.blade.php
@extends('layouts.main')

@section('container')

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Create New Kecamatan</h1>
  </div>

  <div class="col-lg-8">
  <form method="post" action="{{ route('kecamatan.store') }}" class="mb-5" enctype="multipart/form-data">
    @csrf
    <div class="mb-3">
      <label for="kecamatan" class="form-label">Nama</label>
      <input type="text" class="form-control" id="kecamatan"
      name="kecamatan">
    </div>
    <div class="mb-3">
        <label for="provinsi" class="form-tabel">Provinsi</label>
        <select class="form-select" name="provinsi_id">
            @foreach($provinsis as $provinsi)
            @if(old('provinsi_id') == $provinsi->id)
               <option value="{{ $provinsi->id }}" selected>{{ $provinsi->provinsi }}</option>
               @else
               <option value="{{ $provinsi->id }}">{{ $provinsi->provinsi }}</option>
               @endif
            @endforeach
        </select>
      </div>
    <div class="mb-3">
        <label for="Kabupaten" class="form-tabel">Kabupaten</label>
        <select class="form-select" name="kabupaten_id">
            @foreach($kabupatens as $kabupaten)
            @if(old('kabupaten_id') == $kabupaten->id)
               <option value="{{ $kabupaten->id }}" selected>{{ $kabupaten->kabupaten }}</option>
               @else
               <option value="{{ $kabupaten->id }}">{{ $kabupaten->kabupaten }}</option>
               @endif
            @endforeach
        </select>
      </div>
    <button type="submit" class="btn btn-primary">Create Kecamatan</button>
  </form>
</div>
<script>
    const name = document.querySelector('#name');

    name.addEventListener('change', function(){
        fetch('kecamatan/id' + name.value)
        .then(response => response.json())
        .then(data => id.value = data.id)
    });
</script>
@endsection

resources/views/kecamatan/edit.blade.php
@extends('layouts.main')

@section('container')

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Edit Provinsi</h1>
  </div>

  <div class="col-lg-8">
  <form method="post" action="{{ route('kecamatan.update', $kecamatan->id) }}" class="mb-5"
    enctype="multipart/form-data">
    @csrf
    @method('put')
    <div class="mb-3">
        <label for="kecamatan" class="form-label">Nama</label>
        <input type="text" class="form-control" id="kecamatan"
        name="kecamatan">
      </div>
      <div class="mb-3">
          <label for="provinsi" class="form-tabel">Provinsi</label>
          <select class="form-select" name="provinsi_id">
              @foreach($provinsis as $provinsi)
              @if(old('provinsi_id') == $provinsi->id)
                 <option value="{{ $provinsi->id }}" selected>{{ $provinsi->provinsi }}</option>
                 @else
                 <option value="{{ $provinsi->id }}">{{ $provinsi->provinsi }}</option>
                 @endif
              @endforeach
          </select>
        </div>
      <div class="mb-3">
          <label for="Kabupaten" class="form-tabel">Kabupaten</label>
          <select class="form-select" name="kabupaten_id">
              @foreach($kabupatens as $kabupaten)
              @if(old('kabupaten_id') == $kabupaten->id)
                 <option value="{{ $kabupaten->id }}" selected>{{ $kabupaten->kabupaten }}</option>
                 @else
                 <option value="{{ $kabupaten->id }}">{{ $kabupaten->kabupaten }}</option>
                 @endif
              @endforeach
          </select>
        </div>
      <button type="submit" class="btn btn-primary">Update Kecamatan</button>
  </form>
</div>
@endsection

resources/views/kecamatan/index.blade.php
@extends('layouts.main')


@section('container')
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Kecamatan</h1>
  </div>


@if(session()->has('success'))
    <div class="alert alert-success col-lg-6" role="alert">
    {{  session('success') }}
    </div>
@endif
  <div class="table-responsive col-lg-6">
      <a href="{{ route('kecamatan.create') }}" class="btn btn-primary mb-3">Create New Kecamatan</a>
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Name</th>

          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
          @foreach ($kecamatans as $kecamatan)
          <tr>
            <td>{{ $kecamatan->id}}</td>
            <td>{{ $kecamatan->kecamatan}}</td>

            <td>
                <a href="{{ route('kecamatan.edit',$kecamatan->id) }}" class="badge bg-warning">
                <span data-feather="edit"></span></a>
                <form action="{{ route('kecamatan.destroy',$kecamatan->id)}}" method="post" class="d-inline">
                @method('delete')
                @csrf
                <button class="badge bg-danger border-0" onclick="return confirm('Are you sure ?')">
                <span data-feather="x-circle"></span></button>
                </form>
            </td>
          </tr>
          @endforeach

      </tbody>
    </table>
  </div>
@endsection