routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DesaController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProvinsiController;
use App\Http\Controllers\KecamatanController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',[HomeController::class, 'index']);
Route::get('/desa', [DesaController::class, 'index']);
Route::get('/kecamtan', [KecamatanController::class, 'index']);
Route::get('/kabupaten', [KabupatenController::class, 'index']);
Route::get('/provinsi', [ProvinsiController::class, 'index']);


Route::resource('/desa', App\http\Controllers\DesaController::class)->except('show');;
Route::resource('/kecamatan', App\http\Controllers\KecamatanController::class)->except('show');;
Route::resource('/kabupaten', App\http\Controllers\KabupatenController::class)->except('show');;
Route::resource('/provinsi', App\http\Controllers\ProvinsiController::class)->except('show');;

app/Models/desa.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class desa extends Model
{
    use HasFactory;
    protected $fillable = ['id','desa', 'kecamatan_id', 'provinsi_id', 'kabupaten_id'];
    public $timestamps = false;

    public function provinsi(){
        return $this->belongsTo(provinsi::class);
    }

    public function kabupaten(){
        return $this->belongsTo(kabupaten::class);
    }

    public function kecamatan(){
        return $this->belongsTo(kecamatan::class);
    }
}

app/Http/Controllers/DesaController.php
<?php

namespace App\Http\Controllers;

use App\Models\desa;
use App\Models\provinsi;
use App\Models\kabupaten;
use App\Models\kecamatan;
use Illuminate\Http\Request;

class DesaController extends Controller
{
    public function index()
    {

        return view('desa.index',[
        'desas' => Desa::all()
    ]);

    }

    public function create()
    {
        return view('desa.create',[
            'provinsis' => provinsi::all(),
            'kabupatens' => kabupaten::all(),
            'kecamatans' => kecamatan::all()
        ]);

    }

    public function store(Request $request)
    {
        $request->validate([
            'desa' => 'required|string|max:255',
            'provinsi_id' => 'required|integer',
            'kabupaten_id' => 'required|integer',
            'kecamatan_id' => 'required|integer'
        ]);

        Desa::create($request->all());
        return redirect()->route('desa.index')->with('success', 'Desa has been added!');
    }

    public function edit(Desa $desa)
    {
        return view('desa.edit',[
            'desa' => $desa,
            'provinsis' => provinsi::all(),
            'kabupatens' => kabupaten::all(),
            'kecamatans' => kecamatan::all()
        ]);
    }

    public function update(Request $request, Desa $desa)
    {
        $request->validate([
            'desa' => 'required|string|max:255',
            'provinsi_id' => 'required|integer',
            'kabupaten_id' => 'required|integer',
            'kecamatan_id' => 'required|integer'
        ]);

        $desa->update($request->all());

        return redirect()->route('desa.index')->with('success', 'Desa telah berhasil diupdate');


    }

    public function destroy(Desa $desa)
    {
        $desa->delete();

        return redirect()->route('desa.index')->with('Success', 'Desa Berhasil di Hapus');
    }
}

resources/views/desa/create.blade.php
@extends('layouts.main')

@section('container')

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Create New Desa</h1>
  </div>

  <div class="col-lg-8">
  <form method="post" action="{{ route('desa.store') }}" class="mb-5" enctype="multipart/form-data">
    @csrf
    <div class="mb-3">
      <label for="desa" class="form-label">Nama</label>
      <input type="text" class="form-control" id="desa"
      name="desa">
    </div>
    <div class="mb-3">
        <label for="provinsi" class="form-tabel">Provinsi</label>
        <select class="form-select" name="provinsi_id">
            @foreach($provinsis as $provinsi)
            @if(old('provinsi_id') == $provinsi->id)
               <option value="{{ $provinsi->id }}" selected>{{ $provinsi->provinsi }}</option>
               @else
               <option value="{{ $provinsi->id }}">{{ $provinsi->provinsi }}</option>
               @endif
            @endforeach
        </select>
      </div>
    <div class="mb-3">
        <label for="Kabupaten" class="form-tabel">Kabupaten</label>
        <select class="form-select" name="kabupaten_id">
            @foreach($kabupatens as $kabupaten)
            @if(old('kabupaten_id') == $kabupaten->id)
               <option value="{{ $kabupaten->id }}" selected>{{ $kabupaten->kabupaten }}</option>
               @else
               <option value="{{ $kabupaten->id }}">{{ $kabupaten->kabupaten }}</option>
               @endif
            @endforeach
        </select>
      </div>
    <div class="mb-3">
        <label for="kecamatan" class="form-tabel">Kecamatan</label>
        <select class="form-select" name="kecamatan_id">
            @foreach($kecamatans as $kecamatan)
            @if(old('kecamatan_id') == $kecamatan->id)
               <option value="{{ $kecamatan->id }}" selected>{{ $kecamatan->kecamatan }}</option>
               @else
               <option value="{{ $kecamatan->id }}">{{ $kecamatan->kecamatan }}</option>
               @endif
            @endforeach
        </select>
      </div>
    <button type="submit" class="btn btn-primary">Create Desa</button>
  </form>
</div>
@endsection

resources/views/desa/edit.blade.php
@extends('layouts.main')

@section('container')

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Edit Provinsi</h1>
  </div>

  <div class="col-lg-8">
  <form method="post" action="{{ route('desa.update', $desa->id) }}" class="mb-5"
    enctype="multipart/form-data">
    @csrf
    @method('put')
    <div class="mb-3">
        <label for="desa" class="form-label">Nama</label>
        <input type="text" class="form-control" id="desa"
        name="desa">
      </div>
      <div class="mb-3">
          <label for="provinsi" class="form-tabel">Provinsi</label>
          <select class="form-select" name="provinsi_id">
              @foreach($provinsis as $provinsi)
              @if(old('provinsi_id') == $provinsi->id)
                 <option value="{{ $provinsi->id }}" selected>{{ $provinsi->name }}</option>
                 @else
                 <option value="{{ $provinsi->id }}">{{ $provinsi->name }}</option>
                 @endif
              @endforeach
          </select>
        </div>
      <div class="mb-3">
          <label for="Kabupaten" class="form-tabel">Kabupaten</label>
          <select class="form-select" name="kabupaten_id">
              @foreach($kabupatens as $kabupaten)
              @if(old('kabupaten_id') == $kabupaten->id)
                 <option value="{{ $kabupaten->id }}" selected>{{ $kabupaten->name }}</option>
                 @else
                 <option value="{{ $kabupaten->id }}">{{ $kabupaten->name }}</option>
                 @endif
              @endforeach
          </select>
        </div>
      <div class="mb-3">
          <label for="kecamatan" class="form-tabel">Kecamatan</label>
          <select class="form-select" name="kecamatan_id">
              @foreach($kecamatans as $kecamatan)
              @if(old('kecamatan_id') == $kecamatan->id)
                 <option value="{{ $kecamatan->id }}" selected>{{ $kecamatan->name }}</option>
                 @else
                 <option value="{{ $kecamatan->id }}">{{ $kecamatan->name }}</option>
                 @endif
              @endforeach
          </select>
        </div>
      <button type="submit" class="btn btn-primary">Create Desa</button>
  </form>
</div>
@endsection

resources/views/desa/index.blade.php
@extends('layouts.main')


@section('container')
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Desa</h1>
  </div>


@if(session()->has('success'))
    <div class="alert alert-success col-lg-6" role="alert">
    {{  session('success') }}
    </div>
@endif
  <div class="table-responsive col-lg-6">
      <a href="{{ route('desa.create') }}" class="btn btn-primary mb-3">Create New Desa</a>
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Name</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
          @foreach ($desas as $desa)
          <tr>
            <td>{{ $desa->id}}</td>
            <td>{{ $desa->desa}}</td>

            <td>
                <a href="{{ route('desa.edit',$desa->id) }}" class="badge bg-warning">
                <span data-feather="edit"></span></a>
                <form action="{{ route('desa.destroy',$desa->id)}}" method="post" class="d-inline">
                @method('delete')
                @csrf
                <button class="badge bg-danger border-0" onclick="return confirm('Are you sure ?')">
                <span data-feather="x-circle"></span></button>
                </form>
            </td>
          </tr>
          @endforeach

      </tbody>
    </table>
  </div>
@endsection